//===================================================================
// COPYRIGHT  2022/03/02
//===================================================================
// CMCreateWorkingProcedureCmd.cpp
// Header definition of class CMCreateWorkingProcedureCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/02 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateWorkingProcedureCmd_H
#define CMCreateWorkingProcedureCmd_H

#include "CATStateCommand.h"
#include "CATSysBoolean.h"
//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"

#include "CATPathElementAgent.h"
#include "CreateWorkingProcedureDlg.h"

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CMCreateWorkingProcedureCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CMCreateWorkingProcedureCmd, CATStateCommand )

public:
	CMCreateWorkingProcedureCmd();
virtual ~CMCreateWorkingProcedureCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);

virtual CATBoolean OKAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean SelectionCheck();

CATBoolean CheckInput();

HRESULT CreateWorkingProcedure();

HRESULT ReorderOperations();

private:
	CATDialogAgent *_OKAgent;		// OK Button
	CATDialogAgent *_CloseAgent;	// Close Button
	CATDialogAgent *_CancleAgent;	// Cancel Button

	CreateWorkingProcedureDlg * _Panel;

	CATPathElementAgent *_pSelectAgent;


	CATIPLMNavReference * pZWFatherRef;
	CATIPLMNavOccurrence * pZWFatherOcc;
};

//----------------------------------------------------------------------

#endif
