TRANSITIVEBUILT=NO
GProtected=D:\Works\DS\CommomGTO\.\CM_CUSAddin\ProtectedGenerated\win_b64
IProtected=D:\Works\DS\CommomGTO\.\CM_CUSAddin\ProtectedInterfaces
MKMK_BSCMAKE=
IPublic=D:\Works\DS\CommomGTO\.\CM_CUSAddin\PublicInterfaces
GPublic=D:\Works\DS\CommomGTO\.\CM_CUSAddin\PublicGenerated\win_b64
GPrivate=D:\Works\DS\CommomGTO\.\CM_CUSAddin\PrivateGenerated\win_b64
IPrivate=D:\Works\DS\CommomGTO\.\CM_CUSAddin\PrivateInterfaces
WSPATH=D:\Works\DS\CommomGTO\.
FWNAME=CM_CUSAddin
WSROOT=D:\Works\DS\CommomGTO\.
WSSOURCES=D:\Works\DS\CommomGTO\.
WSENAME_msg=CM_CUSAddin
NAME=D:\Works\DS\CommomGTO\.\CM_CUSAddin\IdentityCard\Objects\win_b64\.mkdata.mkb
STEPS_TO_BUILD=CIbuild DoxGrammarFw XrefDB cdg cscinterface dummynls fwcleanup fwgrammar headerlist headermap headerruler xmlctrl
WSEKEY=F_CM_CUSAddin
WSSOURCES_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
FW_AllPreq=AfrFoundation,21ED1151;AfrInterfaces,21ED1151;BSFBuildtimeData,21DD1140;CATImmPPRNavInterfaces,21EE1151;DELPPRAuthFoundationInterfaces,21EE1151;DELPPRLiveProcessInterfaces,21EE1151;DELPPRLiveSystemUseItf,21EE1151;DELWkiExposeUseItf,21EE1151;SpecialAPI,21ED1151;System,21ED1151;AfrComponentsModel,20CC1141;CATPLMComponentInterfaces,20EE1151;CATPLMIdentificationAccess,20CC1151;CATStyleProcessor,20DD1141;CATVirtualVaultSystem,20DD1151;DataCommonProtocolUse,20DD2031;Dialog,20DD1151;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfInterfacesTLB,20EE1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1131;IntrospectionInfrastructure,20CC1141;KnowledgeInterfaces,20EE1151;Mathematics,20DD1131;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerBase,20DD1151;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerSystem,20DD1151;PLMDictionaryInterfaces,20DD1151;SGCoreUtils,20CC1141;SGInfra,20CC1151;SGManager,20CC1151;SystemTS,20CC1131;UIVCoreTools,20DD1131;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationInterfaces,20DD1151;VisualizationSceneGraph,20CC1151;XMLParserItf,20DD1151;
FWCOMPANYNAME=
WS_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=D:\Works\DS\CommomGTO\.\CM_CUSAddin\IdentityCard\Objects\win_b64\.mkHLpath.mk
RTViewDataListPath=D:\Works\DS\CommomGTO\.\CM_CUSAddin\various\win_b64\framework.data
FWCOPYRIGHT=
FW_INCPATH="D:\Works\DS\CommomGTO\.\CM_CUSAddin\PrivateInterfaces" "D:\Works\DS\CommomGTO\.\CM_CUSAddin\PrivateGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CM_CUSAddin\ProtectedInterfaces" "D:\Works\DS\CommomGTO\.\CM_CUSAddin\ProtectedGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CM_CUSAddin\PublicInterfaces" "D:\Works\DS\CommomGTO\.\CM_CUSAddin\PublicGenerated\win_b64"
DOC_RTViewDataListPath=D:\Works\DS\CommomGTO\.\CM_CUSAddin\various\win_b64.doc\framework.data
FWPATH=D:\Works\DS\CommomGTO\.\CM_CUSAddin
FWSOURCES=D:\Works\DS\CommomGTO\.\CM_CUSAddin
STEPS_TO_CLEAN=
F_CM_CUSAddin=mkFrameworkCode "D:\Works\DS\CommomGTO\.\CM_CUSAddin" CM_CUSAddin - -
FWDNAME=CM_CUSAddin
