//===================================================================
// COPYRIGHT  2022/02/09
//===================================================================
// MyStateCommand.cpp
// Header definition of class MyStateCommand
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/09 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MyStateCommand_H
#define MyStateCommand_H

#include "CATStateCommand.h"
#include "CATSysBoolean.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class MyStateCommand: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( MyStateCommand, CATStateCommand )

public:
	MyStateCommand();
virtual ~MyStateCommand();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);

private:

CATIndicationAgent	* _Indication;
};

//----------------------------------------------------------------------

#endif
