//===================================================================
// COPYRIGHT  2022/02/14
//===================================================================
// CMDuplicateGTOOperationCmd.cpp
// Header definition of class CMDuplicateGTOOperationCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/14 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CMDuplicateGTOOperationCmd.h"
#include "CATApplicationFrame.h"
#include "OperationCloneServer.h"
#include "CAAUtility.h"
#include "DELIPPRResourceNav.h"
#include "DELPPRResourceNavAccess.h"
#include "DELIPPRResourceAuth.h"
#include "DELPPRResourceAuthAccess.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CMDuplicateGTOOperationCmd);
#include "PPRUtity.h"
#include "CUSCAAUtilService.h"
#include "PPRUtity.h"
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CMDuplicateGTOOperationCmd::CMDuplicateGTOOperationCmd() :
CATStateCommand ("CMDuplicateGTOOperationCmd", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _OKAgent(NULL),
_ApplyAgent(NULL),
_CloseAgent(NULL),
_CancleAgent(NULL)
{
	CATDlgWindow *pWnd = (CATApplicationFrame::GetFrame())->GetMainWindow();
	_Panel = new CMSystemGTOOperationDuplicateDlg(pWnd, "Duplicate GTO Operation System");
	_Panel->Build();
	_Panel->SetFather(this);

	PushSearchButton = NULL;
	PushAddButton = NULL;
	PushDeleteButton = NULL;
	PushDeleteAllButton = NULL;


	pZWFatherRef = NULL;
	pZWFatherOcc = NULL;

}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CMDuplicateGTOOperationCmd::~CMDuplicateGTOOperationCmd()
{
	if (_OKAgent != NULL)
	{
		_OKAgent->RequestDelayedDestruction();
		_OKAgent = NULL;
	}

	if (_ApplyAgent != NULL)
	{
		_ApplyAgent->RequestDelayedDestruction();
		_ApplyAgent = NULL;
	}

	if (_CloseAgent != NULL)
	{
		_CloseAgent->RequestDelayedDestruction();
		_CloseAgent = NULL;
	}

	if (_CancleAgent != NULL)
	{
		_CancleAgent->RequestDelayedDestruction();
		_CancleAgent = NULL;
	}


	if (_Panel != NULL)
	{
		_Panel->RequestDelayedDestruction();
		_Panel = NULL;
	}

	PushSearchButton = NULL;
	PushAddButton = NULL;
	PushDeleteButton = NULL;
	PushDeleteAllButton = NULL;

	_RELEASE_PTR_(pZWFatherRef);
	_RELEASE_PTR_(pZWFatherOcc);

}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CMDuplicateGTOOperationCmd::BuildGraph()
{
// TODO: Define the StateChart
// ---------------------------
	// Define the OK button agent
	_OKAgent = new CATDialogAgent("OK Agent");
	_OKAgent->AcceptOnNotify(_Panel, _Panel->GetDiaOKNotification());

	// Define the Cancel button agent
	_ApplyAgent = new CATDialogAgent("Apply Agent");
	_ApplyAgent->AcceptOnNotify(_Panel, _Panel->GetDiaAPPLYNotification());   //GetDiaAPPLYNotification     //GetDiaCANCELNotification 

	// Define the Close button agent
	_CloseAgent = new CATDialogAgent("Close Agent");
	_CloseAgent->AcceptOnNotify(_Panel, _Panel->GetWindCloseNotification());    //GetMDICloseNotification    //GetWindCloseNotification

		// Define the Close button agent
	_CancleAgent = new CATDialogAgent("Cancel Agent");
	_CancleAgent->AcceptOnNotify(_Panel, _Panel->GetDiaCANCELNotification());    //GetMDICloseNotification    //GetWindCloseNotification

	// 1-Create Target GTO/JGD agent
	// Define the selection agent
	_pSelectAgent = new CATPathElementAgent("SelectionTargetAgent");
	// Define the behaviors
	_pSelectAgent->SetBehavior(CATDlgEngWithCSO | CATDlgEngWithPrevaluation | CATDlgEngNewHSOManager);   //CATDlgEngMultiAcquisitionCtrl
	CATAcquisitionFilter* pFilterTarget = Filter((FilterMethod)&CMDuplicateGTOOperationCmd::SelectionCheck, (void*)NULL);
	_pSelectAgent->SetFilter(pFilterTarget);
	AddCSOClient(_pSelectAgent);

	// 2-Create source GTO/JGD agent
	// Choose GTO/JGD node from current/other PPR
	_pSelectSourceAgent = new CATOtherDocumentAgent("ElementSelection","CMSampleMultiDocumentGTOOperationCmd", "PlanningStructureService");
	_pSelectSourceAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngNewHSOManager);
	AddCSOClient(_pSelectSourceAgent);
// 	_pSelectSourceAgent = new CATPathElementAgent("SelectionSourceAgent");
// 	_pSelectSourceAgent->SetBehavior(CATDlgEngWithCSO | CATDlgEngWithPrevaluation | CATDlgEngNewHSOManager);
// 	CATAcquisitionFilter* pFilterSource = Filter((FilterMethod)&CMDuplicateGTOOperationCmd::SelectionSourceCheck, (void*)NULL);
// 	_pSelectSourceAgent->SetFilter(pFilterSource);
// 	AddCSOClient(_pSelectSourceAgent);




	// Define the states
	pSelectionState = GetInitialState("ElementSelection");
	pSelectionState->AddDialogAgent(_OKAgent);
	pSelectionState->AddDialogAgent(_CloseAgent);
	pSelectionState->AddDialogAgent(_CancleAgent);
	pSelectionState->AddDialogAgent(_ApplyAgent);
	pSelectionState->AddDialogAgent(_pSelectAgent);
// 	pSelectionState->AddDialogAgent(_pSelectSourceAgent);

  //  In the NLS file, with id=stxxxPointId, you define the message
  //  wich appears in the status bar to indicate how get the xxx point
	stSecondState = AddDialogState("stSecondSourceId");
	stSecondState->AddDialogAgent(_pSelectSourceAgent);

	/**************************************************************/
// 	AddTransition(pSelectionState, pSelectionState, AndCondition(IsOutputSetCondition(_pSelectAgent), IsOutputSetCondition(_pSelectSourceAgent)), Action((ActionMethod)&CMDuplicateGTOOperationCmd::SelectTargetElement, NULL, NULL, (void*)1));

	AddTransition(pSelectionState, stSecondState, IsOutputSetCondition(_pSelectAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::SelectTargetElement, NULL, NULL, (void*)1));
// 	AddTransition(stSecondState, pSelectionState, IsOutputSetCondition(_pSelectSourceAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::SelectSourceElement, NULL, NULL, (void*)1));
	/**************************************************************/



	// Transition from Input state to NULL, when click on OK button
	AddTransition(pSelectionState, NULL, AndCondition(IsOutputSetCondition(_OKAgent), Condition((ConditionMethod)&CMDuplicateGTOOperationCmd::OKAction)), NULL);

	// Transition from Input state to NULL, when click on Apply button
	AddTransition(pSelectionState, pSelectionState, IsOutputSetCondition(_ApplyAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::ApplyAction));

	// Transition from Input state to NULL, when click on Close button
	AddTransition(pSelectionState, NULL, IsOutputSetCondition(_CloseAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::CancelAction));
	AddTransition(pSelectionState, NULL, IsOutputSetCondition(_CancleAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::CancelAction));

// 	AddTransition(pSelectionState, pSelectionState, IsOutputSetCondition(_pSelectAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::ElementSelection, NULL, NULL, (void*)1));

	PushSearchButton = _Panel->GetPushBtn(ID_GTOSearchButton);
	AddAnalyseNotificationCB(PushSearchButton, PushSearchButton->GetPushBActivateNotification(),(CATCommandMethod)&CMDuplicateGTOOperationCmd::PushButtonSearch_Pressed, NULL);

	PushAddButton = _Panel->GetPushBtn(ID_GTOAddButton);
	AddAnalyseNotificationCB(PushAddButton, PushAddButton->GetPushBActivateNotification(),(CATCommandMethod)&CMDuplicateGTOOperationCmd::PushButton_Add_Pressed, NULL);

	PushDeleteButton = _Panel->GetPushBtn(ID_GTODeleteButton);
	AddAnalyseNotificationCB(PushDeleteButton, PushDeleteButton->GetPushBActivateNotification(),(CATCommandMethod)&CMDuplicateGTOOperationCmd::PushButton_Delete_Pressed, NULL);

	PushDeleteAllButton = _Panel->GetPushBtn(ID_GTODeleteAll);
	AddAnalyseNotificationCB(PushDeleteAllButton, PushDeleteAllButton->GetPushBActivateNotification(),(CATCommandMethod)&CMDuplicateGTOOperationCmd::PushButton_DeleteAll_Pressed, NULL);

}

void CMDuplicateGTOOperationCmd::ReBuildOperationRelationShip(CATIPLMNavOccurrence_var spSourceOperationOcc, CATIPLMNavOccurrence_var spNewOperationOcc)
{
	DELIPPRResourceAuth_var hPPRResourceAuth;
	::GetPPRResourceAuth(hPPRResourceAuth);
	DELIPPRResourceNav_var hPPRResourceNav;
	::GetPPRResourceNav(hPPRResourceNav);

	CATListPtrCATBaseUnknown olistResourceOccurrence;
	hPPRResourceNav->GetListWhoResource(spSourceOperationOcc, olistResourceOccurrence);
	for (int i = 1; i <= olistResourceOccurrence.Size(); i++)
	{
		CATIPLMNavOccurrence_var spWhoResourceOcc = olistResourceOccurrence[i];
		hPPRResourceAuth->AssignOperation(spWhoResourceOcc, spNewOperationOcc);
	}

	CATIPLMNavOccurrence * piNavOccOnWhoResource = NULL;
	hPPRResourceNav->GetWhereResource(spSourceOperationOcc, (void **)piNavOccOnWhoResource);
	if (piNavOccOnWhoResource != NULL)
	{
		hPPRResourceAuth->AssignOperation(piNavOccOnWhoResource, spNewOperationOcc);
	}

	CATListPtrCATIPLMNavOccurrence listWithResourceOcc;
	hPPRResourceNav->GetWithResources(spSourceOperationOcc, listWithResourceOcc);
	for (int i = 1; i <= listWithResourceOcc.Size(); i++)
	{
		CATIPLMNavOccurrence* pWithResourceOcc = listWithResourceOcc[i];
		HRESULT rc = hPPRResourceAuth->AssignOperation(pWithResourceOcc, spNewOperationOcc);
		if (FAILED(rc))
		{
			std::cout << "Build relationship between Operation and Resource failed!" << endl;
// 			CUSCAAUtilService::ErrorMessage(CATUnicodeString("Warning"), CATUnicodeString("Warning\nBuild relationship between Operation and Resource failed!\n Please check Resource-System Scope link!"));
		}
	}
}

HRESULT CMDuplicateGTOOperationCmd::insertOP(DuplicateOPStruct newOP)
{
	OperationCloneServer _opCloneServer;
	CATIPLMNavOccurrence_var spCloneOperationOcc = NULL_var;
	_opCloneServer.CloneOperation(pZWFatherOcc, newOP.pOperationRef, spCloneOperationOcc);
	if (spCloneOperationOcc == NULL)
	{
		std::cout << "Failed to clone operation under the system" + newOP.sOperationName << endl;
		return E_FAIL;
	}

	ReBuildOperationRelationShip(newOP.pOperationOcc, spCloneOperationOcc);
	return S_OK;
}

void CMDuplicateGTOOperationCmd::DuplicateOP()
{
	if (pZWFatherRef != NULL)
	{
		auto bound = std::partition(m_vecOperation.begin(), m_vecOperation.end(), [](auto T) ->bool { return T.isDuplicate == TRUE; });
// 		std::for_each(m_vecOperation.begin(), bound, std::bind1st(mem_fun(&CMDuplicateGTOOperationCmd::insertOP), this));	// Correct
		std::for_each(m_vecOperation.begin(), bound, std::bind(&CMDuplicateGTOOperationCmd::insertOP,this, std::placeholders::_1));
	}
}

//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean CMDuplicateGTOOperationCmd::ActionOne( void *data )
{
// TODO: Define the action associated with the transition
// ------------------------------------------------------
	return TRUE;
}

CATBoolean CMDuplicateGTOOperationCmd::SelectionCheck()
{
	CATPathElement *pPath = _pSelectAgent->GetValue();
	CATIPLMNavOccurrence* piOccurrence = (CATIPLMNavOccurrence*)(pPath->FindElement(IID_CATIPLMNavOccurrence));
	if (piOccurrence == NULL)
	{
		return FALSE;
	}
	CATIPLMNavReference *piNavReference = nullptr;
	piOccurrence->GetRelatedReference(piNavReference);
	if (piNavReference == NULL)
	{
		return FALSE;
	}

	CATUnicodeString strObjType = CAAUtility::GetObjectTypeName(piNavReference);

	if (strObjType != "CUS_HeaderOperation_GTO" && strObjType != "CUS_HeaderOperation_JGD")
	{
		return FALSE;
	}

	return TRUE;

}

CATBoolean CMDuplicateGTOOperationCmd::SelectionSourceCheck()
{
	CATPathElement *pPath = _pSelectSourceAgent->GetValue();
	CATIPLMNavOccurrence* piOccurrence = (CATIPLMNavOccurrence*)(pPath->FindElement(IID_CATIPLMNavOccurrence));
	if (piOccurrence == NULL)
	{
		return FALSE;
	}
	CATIPLMNavReference *piNavReference = nullptr;
	piOccurrence->GetRelatedReference(piNavReference);
	if (piNavReference == NULL)
	{
		return FALSE;
	}

	CATUnicodeString strObjType = CAAUtility::GetObjectTypeName(piNavReference);

	if (strObjType != "CUS_HeaderOperation_GTO" && strObjType != "CUS_HeaderOperation_JGD")
	{
		return FALSE;
	}

	return TRUE;

}

CATBoolean CMDuplicateGTOOperationCmd::SelectTargetElement(void *data)
{
	if (_pSelectAgent != NULL)
	{
		CATPathElement * pPathModel = _pSelectAgent->GetValue();
		CATIPLMNavOccurrence* piOccurrence = NULL;
		piOccurrence = (CATIPLMNavOccurrence*)(pPathModel->FindElement(IID_CATIPLMNavOccurrence));
		if (piOccurrence == NULL)
			return TRUE;
		//获取选择节点的参考对象和实例对象
		CATIPLMNavReference *piNavReference = NULL;
		piOccurrence->GetRelatedReference(piNavReference);
		if (piNavReference == NULL)
			return TRUE;

// 		CATUnicodeString Title = "";
// 		CATCkeObjectAttrReadServices::GetValueAsString(piNavReference, "V_Name", Title);
		CATUnicodeString sV_Name = CUSCAAUtilService::GetObjectAttrValue(piNavReference, "V_Name");
		_Panel->GetEditor(ID_GTOTargetEditor)->SetText(sV_Name);


		CATUnicodeString sSelectObjectType = CUSCAAUtilService::GetObjectKnowledgeType(piNavReference);

		if (sSelectObjectType == "CUS_HeaderOperation_GTO" || sSelectObjectType == "CUS_HeaderOperation_JGD")
		{
			pZWFatherRef = piNavReference;
			pZWFatherOcc = piOccurrence;


			_pSelectAgent->InitializeAcquisition();

			_Panel->SetVisibility(CATDlgShow);

		}
	}
	
	
	return TRUE;
}

CATBoolean CMDuplicateGTOOperationCmd::SelectSourceElement(void *data)
{
	if (_pSelectSourceAgent != NULL)
	{
		CATPathElement *pPath = _pSelectSourceAgent->GetValue();
		CATIPLMNavOccurrence* piOccurrence = NULL;
		piOccurrence = (CATIPLMNavOccurrence*)(pPath->FindElement(IID_CATIPLMNavOccurrence));
		if (piOccurrence == NULL) return TRUE;

		CATIPLMNavReference * opiReference = NULL;
		piOccurrence->GetRelatedReference(opiReference);
		if (opiReference != NULL)
		{
			CATUnicodeString sV_Name = CUSCAAUtilService::GetObjectAttrValue(opiReference, "V_Name");
			CATUnicodeString  sPLM_ExternalID = CUSCAAUtilService::GetObjectAttrValue(opiReference, "PLM_ExternalID");

			_Panel->GetEditor(ID_GTOPartNameEdiror)->SetText(sV_Name);
			_Panel->GetEditor(ID_GTOPartCodeEditor)->SetText(sPLM_ExternalID);
		}

		_Panel->GetSelector(ID_GTOOperationsSelectorList)->ClearLine();

		CATListPtrCATIPLMNavOccurrence ioChildrenList;
		piOccurrence->ListChildren(ioChildrenList);		// loop all Operations from GTO
		for (int i = 1; i <= ioChildrenList.Size(); i++)
		{
			DuplicateOPStruct itemOP;
			CATIPLMNavOccurrence*pioChild = ioChildrenList[i];
			CATIPLMNavReference *piChildReference = NULL;

			pioChild->GetRelatedReference(piChildReference);

			CATUnicodeString sOPExternalID = CUSCAAUtilService::GetObjectAttrValue(piChildReference, "PLM_ExternalID");
			CATUnicodeString sOPV_Name = CUSCAAUtilService::GetObjectAttrValue(piChildReference, "V_Name");

			_Panel->GetSelector(ID_GTOOperationsSelectorList)->SetLine(sOPExternalID);


			itemOP.pOperationOcc = pioChild;
			itemOP.pOperationRef = piChildReference;
			itemOP.sOPExternalID = sOPExternalID;
			itemOP.sOperationName = sOPV_Name;
			itemOP.isDuplicate = FALSE;

			m_vecOperation.push_back(itemOP);
		}

		_pSelectSourceAgent->InitializeAcquisition();


	}

	return TRUE;
}

CATBoolean CMDuplicateGTOOperationCmd::OKAction(void *data)
{
	if (_OKAgent)
	{
		_OKAgent->InitializeAcquisition();
	}

	DuplicateOP();
	return TRUE;
}

CATBoolean CMDuplicateGTOOperationCmd::ApplyAction(void *data)
{
	if (_ApplyAgent)
	{
		_ApplyAgent->InitializeAcquisition();
	}
	DuplicateOP();
	return FALSE;
}

CATBoolean CMDuplicateGTOOperationCmd::CancelAction(void *data)
{
	cout << "CMConnectCmd::CancelAction() - INFO: Entering CancelAction()... " << endl;

	if (_Panel != NULL)  _Panel->SetVisibility(CATDlgHide);

	return TRUE;
}


void CMDuplicateGTOOperationCmd::PushButtonSearch_Pressed(void * data)
{
	AddTransition(stSecondState, pSelectionState, IsOutputSetCondition(_pSelectSourceAgent), Action((ActionMethod)&CMDuplicateGTOOperationCmd::SelectSourceElement, NULL, NULL, (void*)1));

	return;
	//////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////

	HRESULT rc = S_OK;
	m_vecOperation.clear();

	CATUnicodeString sInputGTOCode = _Panel->GetEditor(ID_GTOPartCodeEditor)->GetText();
	if (sInputGTOCode.IsNull() == 0)
	{
		CATListPtrCATIAdpPLMIdentificator olistIdentificator;
		//cout<<"GetObjReference ====> iKey:"<< iKey <<endl;
		rc = CUSCAAUtilService::GetObjIdentificator(sInputGTOCode, "", olistIdentificator, "CUS_HeaderOperation_GTO", "PLM_ExternalID");
		if (SUCCEEDED(rc) && olistIdentificator.Size() > 0)
		{
			CATOmbLifeCycleRootsBag LifeCycleBag;
			CATAdpOpenParameters params(CATAdpExpandParameters::Authoring);
			CATAdpOpenParameters::LoadingMode iLoadMode = params.EditMode;
			params.SetLoadingMode(iLoadMode);
			CATAdpOpener opener(LifeCycleBag, params);

			CATAdpComponentData oOpenedComponents;
			rc = opener.CompleteAndOpen(olistIdentificator, oOpenedComponents);

			CATIPLMNavReference * spNavRef = NULL;
			oOpenedComponents.GetComponent(olistIdentificator[1], IID_CATIPLMNavReference, (void**)&spNavRef);


			//////////////////////////////////////////////////////////////////////////
			DELIPPRSystemOccAuth_var hSystemOccAuth(getDELIPPRSystemOccAuth());
			if (hSystemOccAuth == NULL_var) return;

			CATIPLMNavOccurrence* pNavOcc = NULL;
			HRESULT rc = hSystemOccAuth->GetOrCreateRootOccurrence(spNavRef, pNavOcc);		// get Occ

			/************************************************************************/
			/*                                                                      */
			/************************************************************************/
// 			CATIPLMNavOccurrence * pRoot = CUSCAAUtilService::GetRootOcc(pNavOcc);
// 			CATIPLMNavReference * opiReferenceTest = NULL;
// 			pRoot->GetRelatedReference(opiReferenceTest);
// 			CATUnicodeString  sAliasNameTest = CUSCAAUtilService::GetObjectAttrValue(opiReferenceTest, "PLM_ExternalID");
			/************************************************************************/
			/*                                                                      */
			/************************************************************************/
			if (pNavOcc != NULL)
			{
				CATListPtrCATIPLMNavOccurrence ioChildrenList;
				rc = pNavOcc->ListChildren(ioChildrenList);
				for (int i = 1; i <= ioChildrenList.Size(); i ++)
				{
					CATIPLMNavOccurrence* pitem = ioChildrenList[i];

					CATIPLMNavReference * opiReference = NULL;
					pitem->GetRelatedReference(opiReference);

					CATUnicodeString  sAliasName = CUSCAAUtilService::GetObjectAttrValue(opiReference, "PLM_ExternalID");

// 					CATIPLMNavOccurrence_var spCloneOperationOcc = NULL_var;
// 					ReBuildOperationRelationShip(pitem, spCloneOperationOcc);

					DELIPPRResourceAuth_var hPPRResourceAuth;
					::GetPPRResourceAuth(hPPRResourceAuth);
					DELIPPRResourceNav_var hPPRResourceNav;
					::GetPPRResourceNav(hPPRResourceNav);

					CATListPtrCATBaseUnknown olistResourceOccurrence;
					hPPRResourceNav->GetListWhoResource(pitem, olistResourceOccurrence);
					CATIPLMNavOccurrence * piNavOccOnWhoResource = NULL;
					hPPRResourceNav->GetWhereResource(pitem, (void **)piNavOccOnWhoResource);
					CATListPtrCATIPLMNavOccurrence listWithResourceOcc;
					hPPRResourceNav->GetWithResources(pitem, listWithResourceOcc);



				}
			}

			//////////////////////////////////////////////////////////////////////////

			/*
			if (spNavRef != NULL)
			{
				CATUnicodeString  sAliasName = CUSCAAUtilService::GetObjectAttrValue(spNavRef, "PLM_ExternalID");
				_Panel->GetEditor(ID_GTOPartNameEdiror)->SetText(sAliasName);

				// Get all child
				CATListPtrCATIPLMNavEntity opilistIDCompChild;
				CATPLMCoreType coreType = PLMCoreInstance;
				spNavRef->ListChildren(opilistIDCompChild, 0, &coreType);		// 0 = All children are listed.

				_Panel->GetSelector(ID_GTOOperationsSelectorList)->ClearLine();
				for (int i = 1; i <= opilistIDCompChild.Size(); i++)
				{
					CATIPLMNavEntity *pNavEntity = opilistIDCompChild[i];
					CATIPLMNavInstance* piNavInstance = NULL;
					rc = pNavEntity->QueryInterface(IID_CATIPLMNavInstance, (void**)&piNavInstance);
					if (SUCCEEDED(rc))
					{
						DuplicateOPStruct itemOP;
						CATIPLMNavReference* piNavReference = NULL; //IID_CATIPLMNavReference
						rc = piNavInstance->GetReferenceInstanceOf(piNavReference);			// OP Ref


						CATUnicodeString sOpeartionObjectType = CUSCAAUtilService::GetObjectKnowledgeType(piNavReference);

						CATUnicodeString sOPExternalID = CUSCAAUtilService::GetObjectAttrValue(piNavReference, "PLM_ExternalID");
						_Panel->GetSelector(ID_GTOOperationsSelectorList)->SetLine(sOPExternalID);

						CATUnicodeString sOPV_Name = CUSCAAUtilService::GetObjectAttrValue(piNavReference, "V_Name");

						itemOP.sOPExternalID = sOPExternalID;
						itemOP.sOperationName = sOPV_Name;
						itemOP.isDuplicate = FALSE;

						m_vecOperation.push_back(itemOP);
					}
				}
			} */
		}
	}
}

void CMDuplicateGTOOperationCmd::PushButton_Add_Pressed(void * data)
{
	int nSelectItem = _Panel->GetSelector(ID_GTOOperationsSelectorList)->GetSelectCount();
	if (nSelectItem > 0)		// selected one item
	{
		CATUnicodeString sSelectString;
		_Panel->GetSelector(ID_GTOOperationsSelectorList)->GetLine(sSelectString, nSelectItem - 1);

		_Panel->GetSelector(ID_GTOOperationsSelectorList)->ClearLine(nSelectItem - 1);

		// Add new item into Duplicate _SelectorList_GTOOperatoinsDup
		_Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->SetLine(sSelectString);

		VEC_DUPOperation_ITER iter = std::find_if(m_vecOperation.begin(), m_vecOperation.end(), [sSelectString](DuplicateOPStruct T)->bool {
			return T.sOPExternalID == sSelectString;
		});
		iter->isDuplicate = TRUE;
	}
}
void CMDuplicateGTOOperationCmd::PushButton_Delete_Pressed(void * data)
{
	int nSelectItem = _Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->GetSelectCount();
	if (nSelectItem > 0)
	{
		CATUnicodeString sSelectString;
		_Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->GetLine(sSelectString, nSelectItem - 1);

		_Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->ClearLine(nSelectItem - 1);

		_Panel->GetSelector(ID_GTOOperationsSelectorList)->SetLine(sSelectString);

// 		DuplicateOPStruct findItem(sSelectString);
		VEC_DUPOperation_ITER iter = std::find_if(m_vecOperation.begin(), m_vecOperation.end(), [sSelectString](DuplicateOPStruct T)->bool {
			return T.sOPExternalID == sSelectString;
		});
		iter->isDuplicate = FALSE;
	}

}
void CMDuplicateGTOOperationCmd::PushButton_DeleteAll_Pressed(void * data)
{
	if (_Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->GetLineCount() > 0)
	{
		// delete all item
		_Panel->GetSelector(ID_GTOOperationsSelectorList)->ClearLine();
		_Panel->GetSelector(ID_GTOOperatoinsDupSelectorList)->ClearLine();

		std::for_each(m_vecOperation.begin(), m_vecOperation.end(), [this](DuplicateOPStruct &T) {
			this->_Panel->GetSelector(ID_GTOOperationsSelectorList)->SetLine(T.sOPExternalID);
			T.isDuplicate = FALSE;
		});

	}

}


