//===================================================================
// COPYRIGHT  2022/02/12
//===================================================================
// CMCreateGTOBOMSystemCmd.cpp
// Header definition of class CMCreateGTOBOMSystemCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/12 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateGTOBOMSystemCmd_H
#define CMCreateGTOBOMSystemCmd_H

#include "CATStateCommand.h"
#include "CATSysBoolean.h"

#include "CMSystemGTOBOMDlg.h"

#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"
#include "CATListPtrCATIPLMNavReference.h"
#include "CATPathElementAgent.h"

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CMCreateGTOBOMSystemCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CMCreateGTOBOMSystemCmd, CATStateCommand )

public:
	CMCreateGTOBOMSystemCmd();
virtual ~CMCreateGTOBOMSystemCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);

virtual CATBoolean OKAction(void *data);

virtual CATBoolean ApplyAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean ElementSelection(void * data);

void FilterSelectObject();

CATBoolean CheckInputCode();

HRESULT CreateDELGTOBOMSystem();

CATBoolean SelectionCheck();

private:
	CMSystemGTOBOMDlg *_Panel;			// New GTOBOM Dialog

	CATDialogAgent *_OKAgent;		// OK Button
	CATDialogAgent *_ApplyAgent;	// Apply Button
	CATDialogAgent *_CloseAgent;	// Close Button
	CATDialogAgent *_CancleAgent;	// Cancel Button

	CATPathElementAgent *_pSelectAgent;
	CATUnicodeString sInputAOExternalID;


	CATBaseUnknown        * _pSelectedElement;
	CATIPLMNavRepInstance * _pSelectedRepInstance;
	CATIPLMNavOccurrence  * _pSelectedOccurrence;
	CATIPLMNavReference   * _pSelectedReference;

	CATIPLMNavReference * pZWFatherRef;
	CATIPLMNavOccurrence * pZWFatherOcc;

};

//----------------------------------------------------------------------

#endif
