//===================================================================
// COPYRIGHT  2022/02/09
//===================================================================
// CMCreateFTZWSystemCmd.cpp
// Header definition of class CMCreateFTZWSystemCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/09 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateFTZWSystemCmd_H
#define CMCreateFTZWSystemCmd_H

#include "CATStateCommand.h"
#include "CATSysBoolean.h"
#include "CATDialogAgent.h"


#include "CMSystemFTZWDlg.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"

#include "CATPathElementAgent.h"



//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CMCreateFTZWSystemCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CMCreateFTZWSystemCmd, CATStateCommand )

public:
	CMCreateFTZWSystemCmd();
	virtual ~CMCreateFTZWSystemCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);

virtual CATBoolean OKAction(void *data);

virtual CATBoolean ApplyAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean ElementSelection(void * data);

void FilterSelectObject();

CATBoolean CheckZWSelect();
CATBoolean CheckInputCode();

CATBoolean SelectionCheck();

HRESULT CreateDELFTZWSystem();


private:
	CMSystemFTZWDlg *_Panel;		// FTZW Dialog

	CATDialogAgent *_OKAgent;		// OK Button
	CATDialogAgent *_ApplyAgent;	// Apply Button
	CATDialogAgent *_CloseAgent;	// Close Button
	CATDialogAgent *_CancleAgent;	// Cancel Button

	CATPathElementAgent *_pSelectAgent;

	CATUnicodeString sInputAOExternalID;

	CATBaseUnknown        * _pSelectedElement;
	CATIPLMNavRepInstance * _pSelectedRepInstance;
// 	CATIPLMNavInstance	  * _pSelectedInstance;
	CATIPLMNavOccurrence  * _pSelectedOccurrence;
	CATIPLMNavReference   * _pSelectedReference;

	CATIPLMNavReference * pZWFatherRef;
	CATIPLMNavOccurrence * pZWFatherOcc;
};

//----------------------------------------------------------------------

#endif
