//===================================================================
// COPYRIGHT  2022/02/10
//===================================================================
// CMCreateGTOSystemCmd.cpp
// Header definition of class CMCreateGTOSystemCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/10 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateGTOSystemCmd_H
#define CMCreateGTOSystemCmd_H

#include "CATStateCommand.h"
#include "CATSysBoolean.h"

#include "CMSystemGTODlg.h"

#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"

#include "CATPathElementAgent.h"



//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CMCreateGTOSystemCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CMCreateGTOSystemCmd, CATStateCommand )

public:
	CMCreateGTOSystemCmd();
virtual ~CMCreateGTOSystemCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);

virtual CATBoolean OKAction(void *data);

virtual CATBoolean ApplyAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean ElementSelection(void * data);
void FilterSelectObject();

CATBoolean CheckInputCode();

HRESULT CreateDELGTOSystem();
CATBoolean SelectionCheck();

private:
	CMSystemGTODlg *_Panel;			// New GTO Dialog

	CATDialogAgent *_OKAgent;		// OK Button
	CATDialogAgent *_ApplyAgent;	// Apply Button
	CATDialogAgent *_CloseAgent;	// Close Button
	CATDialogAgent *_CancleAgent;	// Cancel Button

	CATPathElementAgent *_pSelectAgent;
	CATUnicodeString sInputAOExternalID;

// 	CATUnicodeString sGTOCard;

	CATUnicodeString sGTOModel;
	CATUnicodeString sGTOBuNumber;
	CATUnicodeString sGTOWorktype;


	CATBaseUnknown        * _pSelectedElement;
	CATIPLMNavRepInstance * _pSelectedRepInstance;
	CATIPLMNavOccurrence  * _pSelectedOccurrence;
	CATIPLMNavReference   * _pSelectedReference;

	CATIPLMNavReference * pZWFatherRef;
	CATIPLMNavOccurrence * pZWFatherOcc;

};

//----------------------------------------------------------------------

#endif
