//===================================================================
// COPYRIGHT  2022/02/08
//===================================================================
// CM_CUSManuEngAddin.cpp
// Header definition of class CM_CUSManuEngAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/08 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCM_CUSManuEngAddin_H
#define ExportedByCM_CUSManuEngAddin_H
#if defined(__CM_CUSManuEngAddin)
# define ExportedByCM_CUSManuEngAddin   DSYExport
#else // __CM_CUSManuEngAddin
# define ExportedByCM_CUSManuEngAddin   DSYImport
#endif  // __CM_CUSManuEngAddin
#include "DSYExport.h"
#endif //ExportedByCM_CUSManuEngAddin_H

