//===================================================================
// COPYRIGHT  2022/02/09
//===================================================================
// PlanningStructureService.cpp
// Header definition of class PlanningStructureService
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/02/09 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByPlanningStructureService_H
#define ExportedByPlanningStructureService_H
#if defined(__PlanningStructureService)
# define ExportedByPlanningStructureService   DSYExport
#else // __PlanningStructureService
# define ExportedByPlanningStructureService   DSYImport
#endif  // __PlanningStructureService
#include "DSYExport.h"
#endif //ExportedByPlanningStructureService_H

