D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\src
D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalInterfaces
D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalGenerated\win_b64
D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PrivateInterfaces
D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\ProtectedInterfaces
D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\BSFBuildtimeData\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\BSFBuildtimeData\PublicInterfaces
D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\PublicInterfaces
D:\Works\DS\CommomGTO\.\CM_UnitityService\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELPPRAuthFoundationInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELPPRAuthFoundationInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\DELPPRResourceItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELPPRResourceItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\DELWkiExposeUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DELWkiExposeUseItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\Dialog\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\Dialog\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\Dialog\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\Dialog\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DialogEngine\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\SpecialAPI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\SpecialAPI\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\SpecialAPI\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\System\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\System\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\System\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\System\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMLegacyInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMLegacyInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMNavInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATImmVPMNavInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUXItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccessItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATPLMUIInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATPLMUIInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATStyleProcessor\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATStyleProcessor\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATView\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATView\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATVirtualVaultSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\CATVirtualVaultSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\CATVirtualVaultSystem\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\IVInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\IVInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\IVInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\InfInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\InfInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\InfInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\InfInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\InfOSIDLItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\InfOSIDLItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\InfOSIDLItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\InfOSIDLItf\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\InteractiveInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\InteractiveInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\InteractiveInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\InteractiveInterfaces\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\IntrospectionInfrastructure\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\IntrospectionInfrastructure\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\IntrospectionInfrastructure\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\IntrospectionInfrastructure\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\Mathematics\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\Mathematics\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\Mathematics\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\MultimediaInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\MultimediaInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\MultimediaPixelImage\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\MultimediaPixelImage\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\MultimediaPixelImage\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\OOCInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerEngines\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerEngines\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerEngines\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\PublicGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMBusinessLogicInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMBusinessLogicInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMDocumentInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMLibraryNavUseItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMManagementInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMManagementInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMManagementServices\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMManagementServices\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMManagementServicesUI\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMManagementServicesUI\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMModelerBaseInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMModelerBaseInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\PLMModelerBaseInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\PLMSetupDataInterfaces\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGCoreUtils\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGCoreUtils\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGInfra\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGInfra\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\SGInfra\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGInfra\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\SGInfra\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGManager\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGManager\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\SGManager\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\SGManager\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\SystemTS\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\SystemTS\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\SystemTS\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\UIVCoreTools\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\UIVCoreTools\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VIAImmersiveViewInterfaces\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VIAImmersiveViewInterfaces\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisuImmersiveDialog\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisuImmersiveDialog\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisuImmersiveDialog\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisuImmersiveDialog\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisuImmersiveDialog\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationController\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationController\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisualizationController\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationCore\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationCore\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationCore\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationFoundation\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationFoundation\PrivateGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisualizationFoundation\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationFoundation\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\VisualizationFoundation\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationSceneGraph\PrivateInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationSceneGraph\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\VisualizationSceneGraph\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\ProtectedInterfaces
C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\ProtectedGenerated\win_b64
C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\PublicInterfaces
C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\PublicGenerated\win_b64
