M_CATMecModLiveUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0FM M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATDialogEngine M_DI0PANV2 M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_CATOmx M_CATPLMIdentificationAccess M_CATPLMComponentInterfaces M_CUS_UtilFunc M_DELPPRSystemItf M_KnowledgeItf M_CATCfgUseItf M_DELPPRProcessItf M_PLMDictionaryNavServices M_CATObjectModelerBase M_ObjectModelerSystem M_CATProviderItf M_CATPLMIntegrationUse M_CATMecModLiveUseItf M_CATMecModUseItf M_DELPPRAuthFoundationItf M_CATProductStructureInterfaces M_DELWkiExposeUseItf M_CATPLMIntegrationAccess M_DELPPRResourceItf M_CAAUtilityMdl
F_CM_ManuEngServiceFrm=mkFrameworkCode "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm" CM_ManuEngServiceFrm - -
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
GProtected=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\ProtectedGenerated\win_b64
IProtected=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\ProtectedInterfaces
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
M_CAAUtilityMdl=mkSharedLibrary "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m" CAAUtilityMdl - - - - - -
GLocal=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalGenerated\win_b64
ILocal=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PublicInterfaces
GPublic=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m
MOD_INCPATH="D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\src" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalInterfaces" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
GPrivate=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PrivateGenerated\win_b64
IPrivate=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PrivateInterfaces
USE_PDB_FILE=YES
M_DELPPRResourceItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRResourceItf\DELPPRResourceItf.m" DELPPRResourceItf - - - - - -
WSPATH=D:\Works\DS\CommomGTO\.
M_CATMecModUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\CATMecModUseItf.m" CATMecModUseItf - - - - - -
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m
FWNAME=CM_ManuEngServiceFrm
WSROOT=D:\Works\DS\CommomGTO\.
CONTNAME=PlanningStructureService
M_DELPPRProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\DELPPRProcessItf.m" DELPPRProcessItf - - - - - -
WSSOURCES=D:\Works\DS\CommomGTO\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
M_CATProductStructureInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\CATProductStructureInterfaces.m" CATProductStructureInterfaces - - - - - -
WSENAME_msg=CM_ManuEngServiceFrm\PlanningStructureService.m
MODDIRNAME=PlanningStructureService.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\Objects\win_b64\.mkdata.mkb
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_PlanningStructureService
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0FM JS0GROUP CATDialogEngine DI0PANV2 CATAfrFoundation CATPLMComponentInterfaces CATVisItf CUS_UtilFunc DELPPRSystemItf KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATObjectModelerBase CATPLMIntegrationUse CATMecModLiveUseItf CATMecModUseItf DELPPRAuthFoundationItf CATProductStructureInterfaces DELWkiExposeUseItf CATPLMIntegrationAccess DELPPRResourceItf CAAUtilityMdl
WSSOURCES_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
M_CATCfgUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUseItf\CATCfgUseItf.m" CATCfgUseItf - - - - - -
M_PlanningStructureService=mkSharedLibrary "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m" PlanningStructureService - - - - - -
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AfrFoundation,21ED1151;BSFBuildtimeData,21DD1140;CAACOMACPublicFrm,11EE1151;CATMecModLiveUseItf,21EE1151;CATMecModUseItf,21EE1151;CATPLMComponentInterfaces,21EE1151;CATPLMConfigUseItf,21EE1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;CM_UnitityService,11EE1151;DELPPRAuthFoundationInterfaces,21EE1151;DELPPRProcessItf,21EE1151;DELPPRResourceItf,21EE1151;DELPPRSystemItf,21EE1151;DELWkiExposeUseItf,21EE1151;Dialog,21EC1151;DialogEngine,21EE1151;KnowledgeInterfaces,21EC1151;ObjectModelerBase,21ED1151;PLMDictionaryNavServices,21ED1151;ProductStructureInterfaces,21EE1151;SpecialAPI,21ED1151;System,21ED1151;VisualizationInterfaces,21ED1151;AfrComponentsModel,20CC1141;AfrInterfaces,20DD1131;CATImmVPMInterfaces,20DD1141;CATImmVPMLegacyInterfaces,20DD1151;CATImmVPMNavInterfaces,20DD1151;CATPLMConfigUXItf,20EE1151;CATPLMIdentificationAccess,20CC1151;CATPLMIntegrationAccessItf,20DD1151;CATPLMIntegrationInterfaces,20DD1151;CATPLMUIInterfaces,20EE1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;DataCommonProtocolUse,20DD2031;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfInterfacesTLB,20EE1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;Mathematics,20DD1131;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerSystem,20DD1151;PLMBusinessLogicInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMDocumentInterfaces,20EE1151;PLMLibraryNavUseItf,20EE1151;PLMManagementInterfaces,20DD1151;PLMManagementServices,20DD1151;PLMManagementServicesUI,20DD1151;PLMModelerBaseInterfaces,20DD1151;PLMSetupDataInterfaces,20EE1151;SGCoreUtils,20CC1141;SGInfra,20CC1151;SGManager,20CC1151;SystemTS,20CC1131;UIVCoreTools,20DD1131;VIAImmersiveViewInterfaces,20DD1151;VisuImmersiveDialog,20CC1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;XMLParserItf,20DD1151;
FWCOMPANYNAME=
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
BUILD=YES
MOD_Container=PlanningStructureService.m
WS_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
RTViewDataListPath=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\various\win_b64\PlanningStructureService.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
BUILT_OBJECT_TYPE=SHARED LIBRARY
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PrivateInterfaces" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PrivateGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\ProtectedInterfaces" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\ProtectedGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PublicInterfaces" "D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PublicGenerated\win_b64"
MOD_SrcPath=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\PlanningStructureService.m\src
M_CUS_UtilFunc=mkSharedLibrary "D:\Works\DS\CommomGTO\.\CM_UnitityService\CUS_UtilFunc.m" CUS_UtilFunc - - - - - -
DOC_RTViewDataListPath=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm\various\win_b64.doc\PlanningStructureService.m\module.data
LINK_WITH=JS0FM JS0GROUP CATDialogEngine DI0PANV2 CATAfrFoundation CATPLMComponentInterfaces CATVisItf CUS_UtilFunc DELPPRSystemItf KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATObjectModelerBase CATPLMIntegrationUse CATMecModLiveUseItf CATMecModUseItf DELPPRAuthFoundationItf CATProductStructureInterfaces DELWkiExposeUseItf CATPLMIntegrationAccess DELPPRResourceItf CAAUtilityMdl
MOD_Included=M_PlanningStructureService
M_DELPPRAuthFoundationItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRAuthFoundationInterfaces\DELPPRAuthFoundationItf.m" DELPPRAuthFoundationItf - - - - - -
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
M_DELWkiExposeUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELWkiExposeUseItf\DELWkiExposeUseItf.m" DELWkiExposeUseItf - - - - - -
FWSOURCES=D:\Works\DS\CommomGTO\.\CM_ManuEngServiceFrm
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
M_DELPPRSystemItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\DELPPRSystemItf.m" DELPPRSystemItf - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=CM_ManuEngServiceFrm
MODNAME=PlanningStructureService
REAL_LINK_WITH=JS0FM JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATDialogEngine DI0PANV2 CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel CATOmx CATPLMIdentificationAccess CATPLMComponentInterfaces CUS_UtilFunc DELPPRSystemItf KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATObjectModelerBase ObjectModelerSystem CATProviderItf CATPLMIntegrationUse CATMecModLiveUseItf CATMecModUseItf DELPPRAuthFoundationItf CATProductStructureInterfaces DELWkiExposeUseItf CATPLMIntegrationAccess DELPPRResourceItf CAAUtilityMdl
