//===================================================================
// COPYRIGHT  2022/03/01
//===================================================================
// CMSampleMultiDocumentGTOOperationCmd.cpp
// Header definition of class CMSampleMultiDocumentGTOOperationCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/03/01 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMSampleMultiDocumentGTOOperationCmd_H
#define CMSampleMultiDocumentGTOOperationCmd_H

#include "CATMultiDocumentCommand.h"
#include "CATPathElementAgent.h"     // for Dialog agent
#include "CATSysBoolean.h"
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATPathElement.h"

// class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CMSampleMultiDocumentGTOOperationCmd: public CATMultiDocumentCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CMSampleMultiDocumentGTOOperationCmd, CATMultiDocumentCommand)

public:
	CMSampleMultiDocumentGTOOperationCmd();
virtual ~CMSampleMultiDocumentGTOOperationCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
virtual CATBoolean  ActionOne(void * data);
CATBoolean SelectionCheck();
private:

	CATPathElementAgent* _AcquisitionAgent;
};

//----------------------------------------------------------------------

#endif
