// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module PlanningStructureService
#======================================================================
#  2022/02/09 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM        \
JS0GROUP \
CATDialogEngine \
DI0PANV2  \ 
CATAfrFoundation \
CATPLMComponentInterfaces \
CATVisItf \
CUS_UtilFunc \
DELPPRSystemItf \
KnowledgeItf \
CATCfgUseItf \
DELPPRProcessItf \
PLMDictionaryNavServices \
CATObjectModelerBase \
CATPLMIntegrationUse \
CATMecModLiveUseItf \
CATMecModUseItf \
DELPPRAuthFoundationItf \
CATProductStructureInterfaces \
DELWkiExposeUseItf \
CATPLMIntegrationAccess \
DELPPRResourceItf \
CAAUtilityMdl \


# END WIZARD EDITION ZONE
