TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATOmx M_CATPLMIdentificationAccess M_CATObjectModelerBase M_ObjectModelerSystem M_CATProviderItf M_CATPLMIntegrationUse M_PLMDocumentInterfacesItf M_CATPLMIntegrationAccess M_PLMDictionaryNavServices M_KnowledgeItf M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_DI0PANV2 M_JS0FM M_CATPLMComponentInterfaces M_DELPPRSystemItf M_DELPPRProcessItf M_CATProductStructureInterfaces M_CATPLMUIInterfaces M_PLMSetupDataInterfaces
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
GProtected=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\ProtectedGenerated\win_b64
IProtected=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\ProtectedInterfaces
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CAAUtilityMdl=mkSharedLibrary "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m" CAAUtilityMdl - - - - - -
GLocal=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\LocalGenerated\win_b64
ILocal=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PublicInterfaces
GPublic=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m
MOD_INCPATH="D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\src" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\LocalInterfaces" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
GPrivate=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PrivateGenerated\win_b64
IPrivate=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PrivateInterfaces
USE_PDB_FILE=YES
WSPATH=D:\Works\DS\CommomGTO\.
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m
FWNAME=CAACOMACPublicFrm
WSROOT=D:\Works\DS\CommomGTO\.
CONTNAME=CAAUtilityMdl
M_DELPPRProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\DELPPRProcessItf.m" DELPPRProcessItf - - - - - -
M_PLMSetupDataInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSetupDataInterfaces\PLMSetupDataInterfaces.m" PLMSetupDataInterfaces - - - - - -
WSSOURCES=D:\Works\DS\CommomGTO\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
M_CATProductStructureInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\CATProductStructureInterfaces.m" CATProductStructureInterfaces - - - - - -
WSENAME_msg=CAACOMACPublicFrm\CAAUtilityMdl.m
MODDIRNAME=CAAUtilityMdl.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\Objects\win_b64\.mkdata.mkb
M_CATPLMUIInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMUIInterfaces\CATPLMUIInterfaces.m" CATPLMUIInterfaces - - - - - -
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_CAAUtilityMdl
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0GROUP CATPLMIdentificationAccess CATObjectModelerBase CATPLMIntegrationUse PLMDocumentInterfacesItf CATPLMIntegrationAccess PLMDictionaryNavServices KnowledgeItf CATAfrFoundation DI0PANV2 JS0FM CATPLMComponentInterfaces DELPPRSystemItf DELPPRProcessItf CATProductStructureInterfaces CATPLMUIInterfaces PLMSetupDataInterfaces
F_CAACOMACPublicFrm=mkFrameworkCode "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm" CAACOMACPublicFrm - -
WSSOURCES_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AfrFoundation,21EE1151;AfrInterfaces,21ED1151;BSFBuildtimeData,21DD1140;CATPLMComponentInterfaces,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;CATPLMUIInterfaces,21EE1151;DELPPRProcessItf,21EE1151;DELPPRSystemItf,21EE1151;DELWkiExposeUseItf,21EE1151;Dialog,21EC1151;KnowledgeInterfaces,21EC1151;ObjectModelerBase,21ED1151;PLMDictionaryNavServices,21ED1151;PLMDocumentInterfaces,21EE1151;PLMSetupDataInterfaces,21EE1151;ProductStructureInterfaces,21EE1151;SpecialAPI,21ED1151;System,21ED1151;SystemTS,21EC1151;AfrComponentsModel,20CC1141;CATImmVPMInterfaces,20DD1141;CATImmVPMLegacyInterfaces,20DD1151;CATImmVPMNavInterfaces,20DD1151;CATPLMIntegrationAccessItf,20DD1151;CATPLMIntegrationInterfaces,20DD1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;DataCommonProtocolUse,20DD2031;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfInterfacesTLB,20EE1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;Mathematics,20DD1131;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerSystem,20DD1151;PLMBusinessLogicInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMManagementInterfaces,20DD1151;PLMManagementServices,20DD1151;PLMManagementServicesUI,20DD1151;PLMModelerBaseInterfaces,20DD1151;SGCoreUtils,20CC1141;SGInfra,20CC1151;SGManager,20CC1151;UIVCoreTools,20DD1131;VIAImmersiveViewInterfaces,20DD1151;VisuImmersiveDialog,20CC1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationInterfaces,20DD1151;VisualizationSceneGraph,20CC1151;XMLParserItf,20DD1151;
FWCOMPANYNAME=
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
BUILD=YES
MOD_Container=CAAUtilityMdl.m
M_PLMDocumentInterfacesItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDocumentInterfaces\PLMDocumentInterfacesItf.m" PLMDocumentInterfacesItf - - - - - -
WS_Concat="D:\Works\DS\CommomGTO\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
RTViewDataListPath=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\various\win_b64\CAAUtilityMdl.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
BUILT_OBJECT_TYPE=SHARED LIBRARY
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PrivateInterfaces" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PrivateGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\ProtectedInterfaces" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\ProtectedGenerated\win_b64" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PublicInterfaces" "D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\PublicGenerated\win_b64"
MOD_SrcPath=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\CAAUtilityMdl.m\src
DOC_RTViewDataListPath=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm\various\win_b64.doc\CAAUtilityMdl.m\module.data
LINK_WITH=JS0GROUP CATPLMIdentificationAccess CATObjectModelerBase CATPLMIntegrationUse PLMDocumentInterfacesItf CATPLMIntegrationAccess PLMDictionaryNavServices KnowledgeItf CATAfrFoundation DI0PANV2 JS0FM CATPLMComponentInterfaces DELPPRSystemItf DELPPRProcessItf CATProductStructureInterfaces CATPLMUIInterfaces PLMSetupDataInterfaces
MOD_Included=M_CAAUtilityMdl
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
FWSOURCES=D:\Works\DS\CommomGTO\.\CAACOMACPublicFrm
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
M_DELPPRSystemItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\DELPPRSystemItf.m" DELPPRSystemItf - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=CAACOMACPublicFrm
MODNAME=CAAUtilityMdl
REAL_LINK_WITH=JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATOmx CATPLMIdentificationAccess CATObjectModelerBase ObjectModelerSystem CATProviderItf CATPLMIntegrationUse PLMDocumentInterfacesItf CATPLMIntegrationAccess PLMDictionaryNavServices KnowledgeItf CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel DI0PANV2 JS0FM CATPLMComponentInterfaces DELPPRSystemItf DELPPRProcessItf CATProductStructureInterfaces CATPLMUIInterfaces PLMSetupDataInterfaces
