//===================================================================
// COPYRIGHT DS 2022/01/26
//===================================================================
// OperationCloneServer.cpp
// Header definition of class OperationCloneServer
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/01/26 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef OperationCloneServer_H
#define OperationCloneServer_H

#include "PlanningStructureService.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavReference.h"
#include "CATListPtrCATIPLMNavReference.h"
//System
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"

#include <iostream>
//-----------------------------------------------------------------------

class ExportedByPlanningStructureService OperationCloneServer
{
public:
// Standard constructors and destructors
// -------------------------------------
OperationCloneServer ();
virtual ~OperationCloneServer ();

int CloneOperation(CATIPLMNavOccurrence_var ispFatherOcc,
					CATIPLMNavReference* ipSourceOperationRef,
					CATIPLMNavOccurrence_var& ospInstantialOpOcc);

void CopyObjectAttributes(CATIPLMNavReference* ipSourceOperationRef, CATIPLMNavReference_var& ispNewOperationRef);

private:
// Copy constructor and equal operator
// -----------------------------------
OperationCloneServer (OperationCloneServer &);
OperationCloneServer& operator=(OperationCloneServer&);


HRESULT CopyWIForOperation(CATIPLMNavReference* ipSourceOperationRef,
							CATIPLMNavOccurrence_var& ispNewOperationOcc);

void CopyWIAttributes(CATIPLMNavReference* ipSourceOperationRef, CATIPLMNavReference*& ipNewOperationRef);


};

//-----------------------------------------------------------------------

#endif
